### ISSUE TITLE
Handling of multiple paragraphs within a content block

### ISSUE THREAD

**Issue by compleatang** [commonform/commonform-commonmark#3]
Currently the parser is very opinionated and combines multiple commonmark paragraphs into a single rendered paragraph within the form. Query the logic here in general and also specifically what are some work arounds when multiple paragraphs are desired within a specific content block? (I'm mostly thinking of, say, the Preamble of a contract in my question).

**Comment by kemitchell** [comment]
Common Form maintains strong separation of content and presentation.

On the content side, the [Common Form JSON schema](https://www.npmjs.com/package/commonform-validate) has no concept of paragraph, only forms that in turn contain content like text, term uses, term definitions, references, blanks, and other forms. When blocks of content need to be meaningfully separated, they're encoded as separate child forms. So a section containing a two subsections is encoded the same as a section containing a two-item list or an article containing two paragraphs.  Regardless of what we call the subdivisions, the structure is:

```
Parent Form (section, article)
│
├─ Child Form (subsection, list item, paragraph)
│
└─ Child Form
```

_Presentation_ of the content in that structure is handled by the renderers, like the [.docx renderer](https://www.npmjs.com/package/commonform-docx), and the numberings they use, like [outline](https://www.npmjs.com/package/outline-numbering) and [decimal](https://www.npmjs.com/package/decimal-numbering).

So the short answer to the end-user question is that if your preamble has multiple blocks of content that need to be meaningfully separated, write them out as sections or list items:

```markdown
# Preamble
- first paragraph of preamble
- second paragraph of preamble

# First Section
first section content...
```

The short answer to the question about this parser could treat paragraphs as child forms, we'd have to come up with a bunch of nuanced rules about when to treat them as child forms and when to treat them as content of the containing form. We'd have to figure out what to do when both paragraphs and list items appear under the same heading.

**Comment by compleatang** [comment]
Thanks as always for the very thorough answer. :-) 

Is there a limit within the form element that restricts the ability to add carriage returns / new lines within the text of a form? I plan to try to find some time to look into this more thoroughly.

**Comment by kemitchell** [comment]
The limit in the form schema that prevents including newlines or carriage returns is here:

https://github.com/commonform/commonform-validate/blob/b13c2331b070c8a34dd30b8928ed3ad364c4dee3/index.js#L26

Note that strings within `content` arrays must consist only of ASCII printable characters in the range `\x20-\x7E`. Line feed (`\x0A`) and carriage return (`\x0D`) fall outside that range, so they aren't allowed.

**Comment by compleatang** [comment]
Got it.
